# Generated by Django 4.2.8 on 2024-02-20 22:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_PROGRESS", "In Progress"),
                            ("FINISHED", "Finished"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="PocketPurpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "party_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="AccountingApp.party",
                    ),
                ),
            ],
            bases=("AccountingApp.party",),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "party_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="AccountingApp.party",
                    ),
                ),
            ],
            bases=("AccountingApp.party",),
        ),
        migrations.CreateModel(
            name="Pocket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.PositiveIntegerField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="AccountingApp.party",
                    ),
                ),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="AccountingApp.pocketpurpose",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoneyMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMMITTED", "Committed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "from_pocket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="money_outgoing",
                        to="AccountingApp.pocket",
                    ),
                ),
                (
                    "to_pocket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="money_incoming",
                        to="AccountingApp.pocket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("WITH_DUE", "With Due"), ("WITHOUT_DUE", "With Due")],
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NOT_DUE", "Not Due"),
                            ("DUE", "Due"),
                            ("PAID", "PAID"),
                        ],
                        default="NOT_DUE",
                        max_length=20,
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("paid_amount", models.PositiveIntegerField(default=0)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resulting_debts",
                        to="AccountingApp.contract",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GharzolHasaneh",
            fields=[
                (
                    "contract_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="AccountingApp.contract",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "lender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gharzes_given",
                        to="AccountingApp.party",
                    ),
                ),
                (
                    "taker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gharzes_taken",
                        to="AccountingApp.party",
                    ),
                ),
            ],
            bases=("AccountingApp.contract",),
        ),
        migrations.CreateModel(
            name="DebtRepayment",
            fields=[
                (
                    "moneymovement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="AccountingApp.moneymovement",
                    ),
                ),
                (
                    "debt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repayments",
                        to="AccountingApp.debt",
                    ),
                ),
            ],
            bases=("AccountingApp.moneymovement",),
        ),
        migrations.CreateModel(
            name="ContractPayment",
            fields=[
                (
                    "moneymovement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="AccountingApp.moneymovement",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="AccountingApp.contract",
                    ),
                ),
            ],
            bases=("AccountingApp.moneymovement",),
        ),
    ]
