# Generated by Django 4.2.8 on 2023-12-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AccountingApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In Progress"),
                    ("COMMITTED", "Committed"),
                    ("FAILED", "Failed"),
                ],
                default="IN_PROGRESS",
                max_length=20,
            ),
        ),
    ]
