# Generated by Django 4.2.8 on 2023-12-06 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AccountingApp", "0002_transaction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_memo",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="entry",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="AccountingApp.account",
            ),
        ),
    ]
